services:
    progrupa.azure.client:
        class: Progrupa\Azure\ApiClient
        arguments:
            - "@progrupa.azure.config"
            - "@progrupa.azure.http"
            - "%progrupa.azure.account_name%"
            - "%progrupa.azure.account_key%"

    progrupa.azure.config:
        class: Progrupa\Azure\Configuration
        public: false


    progrupa.azure.http:
        class: GuzzleHttp\Client
        public: false
        arguments:
            options:
                base_uri: '%progrupa.azure.api_endpoint%'

    progrupa.azure.accounts_api:
        class: Progrupa\Azure\Api\AccountsApi
        arguments:
            - "@progrupa.azure.client"

    progrupa.azure.applications_api:
        class: Progrupa\Azure\Api\ApplicationsApi
        arguments:
            - "@progrupa.azure.client"

    progrupa.azure.certificates_api:
        class: Progrupa\Azure\Api\CertificatesApi
        arguments:
            - "@progrupa.azure.client"

    progrupa.azure.compute_nodes_api:
        class: Progrupa\Azure\Api\ComputeNodesApi
        arguments:
            - "@progrupa.azure.client"

    progrupa.azure.files_api:
        class: Progrupa\Azure\Api\FilesApi
        arguments:
            - "@progrupa.azure.client"

    progrupa.azure.jobs_api:
        class: Progrupa\Azure\Api\JobsApi
        arguments:
            - "@progrupa.azure.client"

    progrupa.azure.job_schedules_api:
        class: Progrupa\Azure\Api\JobSchedulesApi
        arguments:
            - "@progrupa.azure.client"

    progrupa.azure.pools_api:
        class: Progrupa\Azure\Api\PoolsApi
        arguments:
            - "@progrupa.azure.client"

    progrupa.azure.tasks_api:
        class: Progrupa\Azure\Api\TasksApi
        arguments:
            - "@progrupa.azure.client"

