services:
    progrupa.azure.client:
        class: Progrupa\AzureBundle\Azure\Client
        arguments:
            - "@progrupa.azure.http"
            - "%progrupa.azure.account_name%"
            - "%progrupa.azure.account_key%"

    progrupa.azure.http:
        class: GuzzleHttp\Client
        public: false
        arguments:
            options:
                base_uri: '%progrupa.azure.api_endpoint%'
                headers: {Content-Type: 'application/json'}
